query CurrentUserQuery {
	currentUser {
		id
		username
		role
	}
}

mutation LoginUserMutation($username: String!, $password: String!) {
	loginUser(username: $username, password: $password) {
		user {
			id
			username
			role
		}
		token
		expires
	}
}