query CurrentUserQuery {
	currentUser {
		...UserDetail
	}
}

mutation LoginUserMutation($username: String!, $password: String!) {
	loginUser(username: $username, password: $password) {
		user {
			...UserDetail
		}
		token
		expires
	}
}

fragment UserDetail on User {
	id
	username
	role
}