query CurrentUserQuery {
	currentUser {
		...UserDetail
	}
}

mutation LoginUserMutation($username: String!, $password: String!) {
	user: loginUser(username: $username, password: $password) {
		...UserDetail
	}
}

mutation LogoutUserMutation {
	logoutUser
}

fragment UserDetail on User {
	id
	username
	role
}