query GET_ALL_CATALOGS {
	getAllCatalogs {
		id
		name
		title
		company {
			id
			number
			year
		}
		images {
			catalogThumbPath
		}
	}
}

query GET_CURRENT_CATALOGS {
	getAllCatalogs(current: true) {
		id
		name
		title
		company {
			number
			year
			startDate
			finishDate
		}
		images {
			catalogFacePath
		}
	}
}

query GET_CATALOG($company: String!, $name: String!) {
	getCatalog(company: $company, name: $name) {
		title
		originals {
			path
		}
	}
}

mutation ADD_CATALOG($name: String!, $title: String!, $companyId: ID!, $images: [ID]!) {
	addCatalog(name: $name, title: $title, companyId: $companyId, images: $images) {
		id
		name
		title
		company {
			id
			number
			year
		}
		images {
			catalogThumbPath
		}
	}
}

mutation REMOVE_CATALOG($catalogId: ID!, $companyId: ID!) {
	removeCatalog(catalogId: $catalogId, companyId: $companyId)
}