query CatalogsQuery {
	catalogs {
		...CatalogDetail
		company {
			...CompanyDetail
		}
		images {
			id
			catalogThumbPath
		}
	}
}

query CatalogQuery($number: String!, $year: String!, $name: String!) {
	catalog(number: $number, year: $year, name: $name) {
		...CatalogDetail
		images {
			id
			path
			catalogIndex
		}
	}
}

mutation AddCatalogMutation($input: AddCatalogInput!) {
	catalog: addCatalog(input: $input) {
		...CatalogDetail
		company {
			...CompanyDetail
		}
		images {
			id
			catalogThumbPath
		}
	}
}

mutation RemoveCatalogMutation($catalogId: ID!, $companyId: ID!) {
	removeCatalog(catalogId: $catalogId, companyId: $companyId)
}

fragment CatalogDetail on Catalog {
	id
	name
	title
	count
}

fragment CompanyDetail on Company {
	id
	number
	year
}