query CompaniesQuery {
	companies {
		...CompanyDetailFull
	}
}

query CurrentCompanyQuery {
	company: currentCompany {
		...CompanyDetailFull
		catalogs {
			id
			name
			title
			count
			images(limit: 1) {
				id
				catalogFacePath
			}
		}
	}
}

mutation AddCompanyMutation($input: AddCompanyInput!) {
	company: addCompany(input: $input) {
		...CompanyDetailFull
	}
}

mutation RemoveCompanyMutation($id: ID!) {
	removeCompany(id: $id)
}

fragment CompanyDetailFull on Company {
	id
	number
	year
	startDate
	finishDate
}