query CompaniesQuery {
	companies {
		...CompanyDetail
	}
}

query CurrentCompanyQuery {
	company: currentCompany {
		...CompanyDetail
		catalogs {
			id
			name
			count
			images {
				id
				catalogFacePath
			}
		}
	}
}

mutation AddCompanyMutation($input: AddCompanyInput!) {
	company: addCompany(input: $input) {
		...CompanyDetail
	}
}

mutation RemoveCompanyMutation($id: ID!) {
	removeCompany(id: $id)
}

fragment CompanyDetail on Company {
	id
	number
	year
	startDate
	finishDate
}