mutation UPLOAD_CATALOG_IMAGE($catalogName: String!, $companyId: ID!, $companyName: String!, $file: Upload!, $index: Int!) {
	uploadCatalogImage(catalogName: $catalogName, companyId: $companyId, companyName: $companyName, file: $file, index: $index) {
		id
		path
	}
}