query UsersQuery {
	users {
		...UserDetailAdm
	}
}

mutation AddUserMutation($username: String!, $password: String!, $role: String) {
	user: addUser(username: $username, password: $password, role: $role) {
		...UserDetailAdm
	}
}

mutation RemoveUserMutation($id: ID!) {
	removeUser(id: $id)
}

fragment UserDetailAdm on User {
	id
	username
	role
	canBeRemoved
}